from fpdf import FPDF
from data import INSTITUTE_DATA
import os
from datetime import datetime
import uuid
import random

class PDF(FPDF):
    def header(self):
        # Header Background
        self.set_fill_color(79, 70, 229) # Indigo
        self.rect(0, 0, 210, 40, 'F')
        
        self.set_font('Arial', 'B', 20)
        self.set_text_color(255, 255, 255)
        self.cell(0, 15, 'EduNavigator', 0, 1, 'C')
        self.set_font('Arial', 'I', 12)
        self.cell(0, 10, 'Comprehensive Career Analysis Report', 0, 1, 'C')
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by EduNavigator', 0, 0, 'C')

    def section_title(self, title, color=(79, 70, 229)):
        self.ln(5)
        self.set_font('Arial', 'B', 14)
        self.set_text_color(*color)
        self.cell(0, 10, title, 0, 1, 'L')
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def chapter_body(self, body):
        self.set_font('Arial', '', 11)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 6, body)
        self.ln(5)

    def add_bullet_points(self, items):
        self.set_font('Arial', '', 10)
        self.set_text_color(50, 50, 50)
        for item in items:
            self.cell(5)
            self.cell(0, 6, f"- {item}", 0, 1)
        self.ln(3)


    def create_table(self, headers, data, col_widths=None):
        if not col_widths:
            col_widths = [190 // len(headers)] * len(headers)
        
        # Header
        self.set_fill_color(79, 70, 229)
        self.set_font("Arial", "B", 9)
        self.set_text_color(255, 255, 255)
        for i, h in enumerate(headers):
            self.cell(col_widths[i], 8, h, 1, 0, 'C', fill=True)
        self.ln()
        
        # Data
        self.set_font("Arial", "", 9)
        self.set_text_color(0, 0, 0)
        for row in data:
            for i, item in enumerate(row):
                self.cell(col_widths[i], 8, str(item), 1, 0, 'L')
            self.ln()
        self.ln(5)
    
    def create_table_small(self, headers, data, col_widths=None):
        """Table with smaller font for fitting more data"""
        if not col_widths:
            col_widths = [190 // len(headers)] * len(headers)
        
        # Header
        self.set_fill_color(79, 70, 229)
        self.set_font("Arial", "B", 7)
        self.set_text_color(255, 255, 255)
        for i, h in enumerate(headers):
            self.cell(col_widths[i], 7, h, 1, 0, 'C', fill=True)
        self.ln()
        
        # Data
        self.set_font("Arial", "", 7)
        self.set_text_color(0, 0, 0)
        for row in data:
            for i, item in enumerate(row):
                self.cell(col_widths[i], 7, str(item), 1, 0, 'C')
            self.ln()
        self.ln(5)


def generate_study_plan_pdf(user_name, institute_key, category="General"):
    data = INSTITUTE_DATA.get(institute_key)
    if not data:
        return None

    pdf = PDF()
    pdf.add_page()
    
    # Generate unique report ID and timestamp
    report_id = str(uuid.uuid4())[:8].upper()
    generation_time = datetime.now()
    formatted_time = generation_time.strftime("%B %d, %Y at %I:%M %p")
    formatted_date = generation_time.strftime("%Y-%m-%d")
    
    # Personalization Header with Report ID
    pdf.set_font("Arial", "B", 16)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, f"Prepared for: {user_name}", 0, 1, 'L')
    
    # Report Metadata
    pdf.set_font("Arial", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Report ID: {report_id} | Generated: {formatted_time}", 0, 1, 'L')
    pdf.cell(0, 6, f"Data Version: 2025-2026 Academic Year | Last Updated: December 2024", 0, 1, 'L')
    pdf.ln(3)
    
    # Category Information with enhanced styling
    pdf.set_font("Arial", "B", 12)
    pdf.set_fill_color(240, 248, 255)
    pdf.cell(40, 8, "Category:", 0, 0, 'L', fill=True)
    pdf.set_font("Arial", "B", 12)
    pdf.set_text_color(79, 70, 229)
    pdf.cell(0, 8, category, 0, 1, 'L', fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(3)
    
    # Category-specific benefits and personalized analysis
    if category != "General":
        pdf.set_font("Arial", "I", 10)
        pdf.set_text_color(0, 100, 0)
        category_benefits = {
            "OBC": {
                "reservation": "27%",
                "relaxation": "5-10%",
                "description": "OBC candidates benefit from 27% reservation and relaxed cutoffs (typically 5-10% lower than General category).",
                "advantage": "You have a significant advantage with OBC reservation. Your effective competition is reduced by approximately 73%."
            },
            "SC": {
                "reservation": "15%",
                "relaxation": "15-20%",
                "description": "SC candidates get 15% reservation with significant cutoff relaxation (typically 15-20% lower than General).",
                "advantage": "With SC reservation, you compete within a smaller pool and enjoy substantial cutoff relaxation."
            },
            "ST": {
                "reservation": "7.5%",
                "relaxation": "15-20%",
                "description": "ST candidates get 7.5% reservation with significant cutoff relaxation (typically 15-20% lower than General).",
                "advantage": "ST reservation provides you with dedicated seats and considerable cutoff benefits."
            },
            "EWS": {
                "reservation": "10%",
                "relaxation": "2-5%",
                "description": "EWS candidates get 10% reservation with slight cutoff relaxation (typically 2-5% lower than General).",
                "advantage": "EWS reservation gives you access to additional seats beyond the general quota."
            }
        }
        if category in category_benefits:
            benefit = category_benefits[category]
            pdf.set_fill_color(240, 255, 240)
            pdf.multi_cell(0, 5, f">> Reservation Benefit: {benefit['description']}", 0, 'L', fill=True)
            pdf.ln(2)
            pdf.set_font("Arial", "B", 10)
            pdf.set_text_color(0, 100, 200)
            pdf.multi_cell(0, 5, f"Your Advantage: {benefit['advantage']}")
        pdf.set_text_color(0, 0, 0)
        pdf.ln(5)
    else:
        # General category note
        pdf.set_font("Arial", "I", 9)
        pdf.set_text_color(100, 100, 100)
        pdf.multi_cell(0, 5, "Note: You are applying under General category. Cutoffs shown are for General category candidates.")
        pdf.set_text_color(0, 0, 0)
        pdf.ln(5)
    
    # Institute Overview
    pdf.section_title(f"Target Institute: {data['name']}")
    pdf.chapter_body(data['description'])
    
    # Premium Institutes List
    pdf.set_fill_color(240, 240, 255)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "Top Premium Institutes", 0, 1, 'L', fill=True)
    pdf.ln(2)
    pdf.add_bullet_points(data['premium_institutes'])
    
    # Detailed IIT Rankings (if available)
    if 'detailed_iit_rankings' in data:
        pdf.add_page()
        pdf.section_title("Detailed Institute Rankings & Analysis", (220, 20, 60))
        
        for iit_info in data['detailed_iit_rankings']:
            pdf.set_fill_color(245, 245, 250)
            pdf.set_font("Arial", "B", 12)
            pdf.cell(0, 8, f"{iit_info['iit']} - Rank #{iit_info['rank']}", 0, 1, 'L', fill=True)
            pdf.ln(2)
            
            pdf.set_font("Arial", "B", 10)
            pdf.cell(50, 6, "Location:", 0, 0)
            pdf.set_font("Arial", "", 10)
            pdf.cell(0, 6, iit_info['location'], 0, 1)
            
            pdf.set_font("Arial", "B", 10)
            pdf.cell(50, 6, "Cutoff Range:", 0, 0)
            pdf.set_font("Arial", "", 10)
            pdf.cell(0, 6, iit_info['general_cutoff_rank'], 0, 1)
            
            pdf.set_font("Arial", "B", 10)
            pdf.cell(50, 6, "CSE Cutoff:", 0, 0)
            pdf.set_font("Arial", "", 10)
            pdf.cell(0, 6, iit_info['cse_cutoff'], 0, 1)
            
            pdf.set_font("Arial", "B", 10)
            pdf.cell(50, 6, "Key Specialties:", 0, 0)
            pdf.set_font("Arial", "", 10)
            pdf.multi_cell(0, 6, iit_info['key_specialties'])
            
            pdf.set_font("Arial", "B", 10)
            pdf.cell(50, 6, "Avg Package:", 0, 0)
            pdf.set_font("Arial", "", 10)
            pdf.cell(60, 6, iit_info['avg_package'], 0, 0)
            pdf.set_font("Arial", "B", 10)
            pdf.cell(40, 6, "Highest:", 0, 0)
            pdf.set_font("Arial", "", 10)
            pdf.cell(0, 6, iit_info['highest_package'], 0, 1)
            
            pdf.set_font("Arial", "I", 9)
            pdf.set_text_color(100, 100, 100)
            pdf.multi_cell(0, 5, iit_info['special_notes'])
            pdf.set_text_color(0, 0, 0)
            pdf.ln(4)
    
    # Branch-wise Details (if available)
    if 'branch_wise_details' in data:
        pdf.add_page()
        pdf.section_title("Branch-wise Analysis", (0, 128, 0))
        
        for branch, details in data['branch_wise_details'].items():
            pdf.set_fill_color(240, 255, 240)
            pdf.set_font("Arial", "B", 11)
            pdf.cell(0, 7, branch, 0, 1, 'L', fill=True)
            pdf.ln(1)
            
            pdf.set_font("Arial", "B", 9)
            pdf.cell(50, 6, "Cutoff Range:", 0, 0)
            pdf.set_font("Arial", "", 9)
            pdf.cell(0, 6, details['cutoff_range'], 0, 1)
            
            pdf.set_font("Arial", "B", 9)
            pdf.cell(50, 6, "Avg Package:", 0, 0)
            pdf.set_font("Arial", "", 9)
            pdf.cell(60, 6, details['avg_package'], 0, 0)
            pdf.set_font("Arial", "B", 9)
            pdf.cell(40, 6, "Highest:", 0, 0)
            pdf.set_font("Arial", "", 9)
            pdf.cell(0, 6, details['highest_package'], 0, 1)
            
            pdf.set_font("Arial", "B", 9)
            pdf.cell(50, 6, "Top Companies:", 0, 0)
            pdf.set_font("Arial", "", 9)
            pdf.multi_cell(0, 6, ", ".join(details['top_companies']))
            
            pdf.set_font("Arial", "B", 9)
            pdf.cell(50, 6, "Career Paths:", 0, 0)
            pdf.set_font("Arial", "", 9)
            pdf.multi_cell(0, 6, ", ".join(details['career_paths']))
            pdf.ln(3)
    
    # Entrance Exam Details
    if 'entrance_exam_details' in data:
        pdf.add_page()
        exam = data['entrance_exam_details']
        pdf.section_title("Entrance Exam Comprehensive Guide", (220, 20, 60))
        
        pdf.set_font("Arial", "B", 11)
        pdf.cell(50, 8, "Exam Name:", 0, 0)
        pdf.set_font("Arial", "", 11)
        pdf.cell(0, 8, exam['name'], 0, 1)
        
        if 'eligibility' in exam:
            pdf.set_font("Arial", "B", 11)
            pdf.cell(50, 8, "Eligibility:", 0, 0)
            pdf.set_font("Arial", "", 11)
            pdf.multi_cell(0, 8, exam['eligibility'])
        
        pdf.set_font("Arial", "B", 11)
        pdf.cell(50, 8, "Duration:", 0, 0)
        pdf.set_font("Arial", "", 11)
        pdf.cell(0, 8, exam['duration'], 0, 1)
        
        if 'total_marks' in exam:
            pdf.set_font("Arial", "B", 11)
            pdf.cell(50, 8, "Total Marks:", 0, 0)
            pdf.set_font("Arial", "", 11)
            pdf.cell(0, 8, exam['total_marks'], 0, 1)
        
        pdf.set_font("Arial", "B", 11)
        pdf.cell(50, 8, "Pattern:", 0, 1)
        pdf.set_font("Arial", "", 11)
        pdf.multi_cell(0, 6, exam['pattern'])
        pdf.ln(2)
        
        pdf.set_font("Arial", "B", 11)
        pdf.cell(50, 8, "Marking Scheme:", 0, 1)
        pdf.set_font("Arial", "", 11)
        pdf.multi_cell(0, 6, exam['marking_scheme'])
        pdf.ln(2)
        
        if 'difficulty_level' in exam:
            pdf.set_font("Arial", "B", 11)
            pdf.cell(50, 8, "Difficulty:", 0, 0)
            pdf.set_font("Arial", "", 11)
            pdf.cell(0, 8, exam['difficulty_level'], 0, 1)
        
        if 'preparation_time' in exam:
            pdf.set_font("Arial", "B", 11)
            pdf.cell(50, 8, "Prep Time:", 0, 0)
            pdf.set_font("Arial", "", 11)
            pdf.cell(0, 8, exam['preparation_time'], 0, 1)
        
        if 'success_rate' in exam:
            pdf.set_font("Arial", "B", 11)
            pdf.cell(50, 8, "Success Rate:", 0, 0)
            pdf.set_font("Arial", "", 11)
            pdf.cell(0, 8, exam['success_rate'], 0, 1)

    # Cutoff Analysis Table - Category Specific
    cutoff_data = None
    if 'cutoff_analysis_by_category' in data and category in data['cutoff_analysis_by_category']:
        cutoff_data = data['cutoff_analysis_by_category'][category]
        pdf.add_page()
        pdf.section_title(f"Cutoff Analysis & Historical Trends ({category} Category)", (220, 20, 60))
        
        # Add category note
        pdf.set_font("Arial", "I", 10)
        pdf.set_text_color(0, 100, 200)
        pdf.multi_cell(0, 6, f"Note: These cutoffs are specific to {category} category. Cutoffs vary significantly across categories due to reservation policies.")
        pdf.set_text_color(0, 0, 0)
        pdf.ln(3)
    elif 'cutoff_analysis' in data:
        cutoff_data = data['cutoff_analysis']
        pdf.add_page()
        pdf.section_title("Cutoff Analysis & Historical Trends")
    
    if cutoff_data:
        headers = ["Year", "Trend"]
        # Get all unique keys from cutoff data
        all_keys = set()
        for row in cutoff_data:
            all_keys.update([k for k in row.keys() if k not in ['year', 'trend']])
        
        # Add dynamic headers
        for key in sorted(all_keys):
            headers.append(key.replace('_', ' ').title())
        
        table_data = []
        for row in cutoff_data:
            row_data = [row.get('year', '-'), row.get('trend', '-')]
            for key in sorted(all_keys):
                row_data.append(row.get(key, '-'))
            table_data.append(row_data)
        
        
        # Calculate column widths - optimized for cutoff table
        # Year: 20, Trend: 20, Each cutoff column gets equal share of remaining space
        num_cutoff_cols = len(all_keys)
        if num_cutoff_cols > 0:
            # Total available width: 190, minus Year(20) and Trend(20) = 150 for cutoff columns
            cutoff_col_width = 150 // num_cutoff_cols
            col_widths = [20, 20] + [cutoff_col_width] * num_cutoff_cols
        else:
            col_widths = [30, 25]
        
        # Use smaller font for cutoff table to fit data
        pdf.create_table_small(headers, table_data, col_widths)

    # Career Progression
    if 'career_progression' in data:
        pdf.section_title("Career Progression Roadmap")
        pdf.set_font("Arial", "", 10)
        for year, desc in data['career_progression'].items():
            pdf.set_font("Arial", "B", 11)
            pdf.set_fill_color(240, 248, 255)
            pdf.cell(35, 8, year, 0, 0, 'L', fill=True)
            pdf.set_font("Arial", "", 10)
            pdf.multi_cell(0, 8, desc)
            pdf.ln(2)

    # Campus Facilities (if available)
    if 'campus_facilities' in data:
        pdf.add_page()
        pdf.section_title("Campus Facilities & Infrastructure", (0, 100, 200))
        facilities = data['campus_facilities']
        
        for facility, details in facilities.items():
            pdf.set_font("Arial", "B", 10)
            pdf.cell(40, 7, f"{facility.title()}:", 0, 0)
            pdf.set_font("Arial", "", 10)
            pdf.multi_cell(0, 7, details)
            pdf.ln(1)

    # ROI Analysis
    if 'roi_analysis' in data:
        pdf.add_page()
        pdf.section_title("Return on Investment (ROI) Analysis", (0, 128, 0))
        roi = data['roi_analysis']
        
        headers = ["Metric", "Details"]
        table_data = []
        for key, value in roi.items():
            metric_name = key.replace('_', ' ').title()
            table_data.append([metric_name, value])
        
        pdf.create_table(headers, table_data, [70, 120])

    # Placement Statistics (if available)
    if 'placement_statistics' in data:
        pdf.section_title("Placement Statistics", (220, 20, 60))
        stats = data['placement_statistics']
        
        for key, value in stats.items():
            pdf.set_font("Arial", "B", 10)
            pdf.cell(60, 7, f"{key.replace('_', ' ').title()}:", 0, 0)
            pdf.set_font("Arial", "", 10)
            if isinstance(value, list):
                pdf.multi_cell(0, 7, ", ".join(value))
            else:
                pdf.cell(0, 7, str(value), 0, 1)

    # Skill Matrix
    if 'skill_matrix' in data:
        pdf.add_page()
        pdf.section_title("Skill Development Matrix")
        skills = data['skill_matrix']
        
        pdf.set_font("Arial", "B", 11)
        pdf.set_fill_color(255, 240, 240)
        pdf.cell(0, 8, "Technical Skills:", 0, 1, 'L', fill=True)
        pdf.set_font("Arial", "", 10)
        pdf.multi_cell(0, 6, ", ".join(skills.get('technical', [])))
        pdf.ln(2)
        
        pdf.set_font("Arial", "B", 11)
        pdf.set_fill_color(240, 255, 240)
        pdf.cell(0, 8, "Soft Skills:", 0, 1, 'L', fill=True)
        pdf.set_font("Arial", "", 10)
        pdf.multi_cell(0, 6, ", ".join(skills.get('soft_skills', [])))
        pdf.ln(2)
        
        pdf.set_font("Arial", "B", 11)
        pdf.set_fill_color(240, 240, 255)
        pdf.cell(0, 8, "Future Ready Skills:", 0, 1, 'L', fill=True)
        pdf.set_font("Arial", "", 10)
        pdf.multi_cell(0, 6, ", ".join(skills.get('future_ready', [])))

    # Top Recruiters
    if 'top_recruiters' in data:
        pdf.add_page()
        pdf.section_title("Top Recruiters by Sector", (0, 100, 200))
        for sector, companies in data['top_recruiters'].items():
            pdf.set_font("Arial", "B", 10)
            pdf.set_fill_color(245, 245, 250)
            pdf.cell(50, 7, f"{sector}:", 0, 0, 'L', fill=True)
            pdf.set_font("Arial", "", 10)
            pdf.multi_cell(0, 7, ", ".join(companies))
            pdf.ln(1)

    # Alumni Network (if available)
    if 'alumni_network' in data:
        pdf.section_title("Alumni Network & Notable Alumni")
        alumni = data['alumni_network']
        
        for key, value in alumni.items():
            pdf.set_font("Arial", "B", 10)
            pdf.cell(50, 7, f"{key.replace('_', ' ').title()}:", 0, 0)
            pdf.set_font("Arial", "", 10)
            if isinstance(value, list):
                pdf.multi_cell(0, 7, ", ".join(value))
            else:
                pdf.cell(0, 7, str(value), 0, 1)

    # Research Opportunities (if available)
    if 'research_opportunities' in data:
        pdf.section_title("Research Opportunities", (128, 0, 128))
        research = data['research_opportunities']
        
        for key, value in research.items():
            pdf.set_font("Arial", "B", 10)
            pdf.cell(60, 7, f"{key.replace('_', ' ').title()}:", 0, 0)
            pdf.set_font("Arial", "", 10)
            pdf.multi_cell(0, 7, str(value))

    # Student Life (if available)
    if 'student_life' in data:
        pdf.section_title("Student Life & Culture")
        life = data['student_life']
        
        for key, value in life.items():
            pdf.set_font("Arial", "B", 10)
            pdf.cell(50, 7, f"{key.title()}:", 0, 0)
            pdf.set_font("Arial", "", 10)
            pdf.multi_cell(0, 7, str(value))
            pdf.ln(1)

    # Recommendations
    if 'recommendations' in data:
        pdf.add_page()
        pdf.section_title("Strategic Recommendations & Success Tips", (0, 128, 0))
        pdf.set_text_color(0, 100, 0)
        pdf.add_bullet_points(data['recommendations'])
        pdf.set_text_color(0, 0, 0)

    # Locations & Courses
    pdf.add_page()
    pdf.section_title("Locations & Courses Offered")
    pdf.set_font("Arial", "B", 11)
    pdf.cell(0, 8, "Locations:", 0, 1)
    pdf.set_font("Arial", "", 10)
    pdf.multi_cell(0, 6, ", ".join(data['locations']))
    pdf.ln(2)
    
    pdf.set_font("Arial", "B", 11)
    pdf.cell(0, 8, "Courses Offered:", 0, 1)
    pdf.set_font("Arial", "", 10)
    pdf.multi_cell(0, 6, ", ".join(data['courses']))
    
    filename = f"Study_Plan_{user_name.replace(' ', '_')}_{institute_key}.pdf"
    filepath = os.path.join("static", filename)
    pdf.output(filepath)
    return filepath
